version: "3"

services:
  app:
    image: health-tracker-app
    container_name: health-tracker-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - redis
      - mariadb
    env_file:
      - .docker.env
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    environment:
      APP_ENV: local
      CONTAINER_ROLE: app

  scheduler:
    image: health-tracker-app
    container_name: health-tracker-scheduler
    depends_on:
      - app
      - redis
      - mariadb
    env_file:
      - .docker.env
    volumes:
      - .:/var/www/html
    environment:
      CONTAINER_ROLE: scheduler
      APP_ENV: local

  queue:
    image: health-tracker-app
    container_name: health-tracker-queue
    depends_on:
      - app
      - redis
      - mariadb
    env_file:
      - .docker.env
    volumes:
      - .:/var/www/html
    environment:
      CONTAINER_ROLE: queue
      APP_ENV: local

  redis:
    container_name: health-tracker-redis
    image: redis:6-alpine
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis:/data

  mariadb:
    container_name: health-tracker-mariadb
    image: mariadb:10.7
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb:/var/lib/mysql
    environment:
        MARIADB_DATABASE: ${DB_DATABASE}
        MARIADB_ROOT_PASSWORD : ${DB_ROOT_PASSWORD}
        MARIADB_USER: ${DB_USERNAME}
        MARIADB_PASSWORD : ${DB_PASSWORD}

volumes:
  redis:
    driver: "local"
  mariadb:
    driver: "local"
